[package]
name = "libsettings"
version = "0.1.0"
authors = ["Jason Mobarak <jason@swift-nav.com>"]
edition = "2018"

[dependencies]
libc = "0.2"
lazy_static = "1.3"

[build-dependencies]
bindgen = "0.54"
cmake = "*"
