[package]
name = "libsettings"
version = "0.1.0"
authors = ["Jason Mobarak <jason@swift-nav.com>"]
edition = "2018"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_yaml = "0.8"
libc = "0.2"
clap = { version = "2", features = ["yaml"] }
yaml-rust = "0.4"
lazy_static = "1.3"

[build-dependencies]
bindgen = "0.54"
cmake = "*"
