name: Rust
on: [ push, pull_request ]
env:
  LIBCLANG_PATH_WIN: "C:/Program Files (x86)/Microsoft Visual Studio/2019/Enterprise/VC/Tools/Llvm/x64/bin"
jobs:
  test:
    name: Tests
    strategy:
      matrix:
        build-type: [Release]
        os:
          - windows-2019
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - uses: bwoodsend/setup-winlibs-action@v1
        with:
          destination: c:/

      - name: Find mingw
        shell: bash
        run: |
          which g++
          ls C:/ProgramData/chocolatey/lib/mingw/tools/install/mingw64/include
          ls c:/
          ls c:/mingw64
          ls c:/mingw64/include
          set

      - name: Install msys2 packages
        uses: msys2/setup-msys2@v2
        with:
          msystem: MINGW64
          install: git base-devel
          update: true

      - name: Install MinGW Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: x86_64-pc-windows-gnu
          override: true
          components: rustfmt, clippy

      - name: Run tests
        env:
          LIBCLANG_PATH: ${{ env.LIBCLANG_PATH_WIN }}
          CC: gcc
          CXX: g++
          TESTENV: rust
          OS_NAME: windows
          CMAKE_GENERATOR: MinGW Makefiles
        run: cargo test --target=x86_64-pc-windows-gnu
